---
- hosts: all
  become: yes

  roles:
    - role: user
      tags:
        - user
    - role: dotfiles
      tags:
        - dotfiles
    - role: packages
      tags:
        - packages
    - role: cleanup
      tags:
        - cleanup
