---
- name: users | create a login user group
  group:
    name: "{{ username }}"
    state: present

- name: users | create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    group: "{{ username }}"
    groups: "{{ sudo_group }}"
    shell: "{{ shell }}"
    state: present

- name: users | add temporary sudoers file
  template:
    src: sudoers_passwordless
    dest: /etc/sudoers.d/sudoers_passwordless
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s

- name: users | remove preinstalled clutter from home directory
  file:
    path: /home/{{ username }}/{{ item }}
    state: absent
  with_items:
    - .bashrc
    - .bash_logout
    - .bash_profile
