- name: cleanup | enable power-profiles-daemon service
  systemd:
    name: power-profiles-daemon.service
    enabled: yes

- name: cleanup | remove passwordless sudo for installed user
  file:
    path: /etc/sudoers.d/sudoers_passwordless
    state: absent

- name: cleanup | add sudoers file
  template:
    src: 00-user-can-sudo
    dest: /etc/sudoers.d/00-user-can-sudo
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
